server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/BnoAsset?serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: user
    password: 1234

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
